### ISSUE TITLE
switch to new tado authentication server

### ISSUE THREAD

**Issue by elmi82** [steffjenl/laravel-tado#3]
tado is discontinuing the old OAuth2 endpoints at `my.tado.com`. Starting March 2019, authentication will require retrieving access and refresh tokens from `auth.tado.com`. The client `public-api-preview` can be used as is (with the same client secret) on the new endpoint.

The new authentication will also be a standard OAuth2 system, but will use JWT as a format for refresh tokens. So be aware that this will increase the size of the refresh tokens.

Additionally, the new endpoints implement [refresh token rotation](https://tools.ietf.org/html/rfc6749#section-10.4). A new refresh token is issued with every access token refresh response. The previous refresh token is invalidated.

**Comment by steffjenl** [comment]
@elmi82 is there documentation available? when will the new endpoints available on auth.tado.com?

OAuth2 client is already using auth.tado.com, only the data endpoints are using my.tado.com so nothing will change for this package?

**Comment by elmi82** [comment]
@steffjenl - the new endpoints are already available on `auth.tado.com`, it should be enough to switch the URL (`auth.tado.com` is a OAuth2 compliant OAuth server).

Please note, that this only concerns the authorization part (getting and refreshing access tokens). The API endpoints to control tado or retrieve current state remain on `my.tado.com`. There's no public documentation available, but good resources are [tado-api.yaml](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.tado/src/main/api/tado-api.yaml) or http://blog.scphillips.com/posts/2017/01/the-tado-api-v2/

**Comment by elmi82** [comment]
@steffjenl Sorry, just read (and understood) the last part of your previous message. If you already get the tokens from `auth.tado.com` no further changes are necessary and this issue can be closed

**Comment by steffjenl** [comment]
@elmi82 thank you!
